= Politics and Setting
:showtitle!:

toc::[]

== Lockport:
[abstract]
--
Our Refinery Powers the World
--

The westernmost port of Skovlan, Lockport has a long and bloody history, its crimes too recent to have been dulled by memory.

Unable to see the honor in being selected as the home for the Refineries and Manufactories that turn Leviathan Blood into power, Lockport led the Skovlan rebellion, beginning the Unity War.

Spanning nearly 40 years, and costing countless lives, the war ended only when a brave hero risked everything to rid the world of the rebellious so-called Queen Alayne, and once again bringing Skovlan firmly under the control of the Immortal Emperor, may we be worthy of his Sunlight.

Now aware of the favor it has been granted, Lockport’s Refineries and Manufactories once again produce power and products for the rest of the Empire. They do, of course, shoulder a much larger burden of taxation. This is by no means punitive! Rather, it is simply compensation for the years they deprived the Empire of their labors and service.

Many of Lockport’s citizens fled during the war, risking the dangers of the Sea to shelter in the security of Doskvol’s open arms. Now, they are slowly returning, but Lockport has suffered a shortage of labor. To remedy that, the Ministry of Preservation is importing able bodied workers owing a debt to the Empire. While the citizenry of Lockport might object, they have a poor understanding of exactly how necessary this is to continue to support the reclamation of the city.


== The Six Families and the Council Accords
Though Lockport is once again firmly in the hands of the Immortal Emperor, may we be worthy of his Sunlight, as the flashpoint for the Unity War, it has seen more than its share of upheaval. Since the end of the war two years ago, the city has managed to begin to pick up the pieces of self government. Last year, by decree of the Emperor, may we be worthy of his Sunlight, it was once again granted limited self-governance.

Being denied a single leader, Lockport’s preeminent families have created a Council, with one member chosen from each of the Six. The Council is guided by the so-called Council Accords, formalized, legal agreements delineating each family’s scope of power, and creating a detant of influence among them.

With each Family agreeing to claim only on seat on the City Council, as well as restraining their dominance to one element of the city’s functions, a tentative equilibrium has been reached. For now, at least, no one has pushed too far in any one direction, encroached too much on another’s territory. Yes, the Families nibble away at each other, but just as perfectly balanced boulders hold back the avalanche, their encroachments have remained aligned.

However, as with everything, that alignment is fragile. At any time, a Family could press too far, take too much of what another holds. A complex web of marriages, business partnerships, and alliances have thus far held back a change of tide, but nothing in this world is static.

To the man on the street, or in the gutter, the Families division of the city has had a variety of effects.

Some neither know nor care who live in the clean, well-lit houses, and claim to “own” their streets. Some are too busy getting by to care for anything more than a stable price for bread.

Some, mainly those gangs who grasp for pride and a sense of identity feel strongly aligned to the Family that governs their particular specialty, or part of the city. The Bravos of [location] for example, might take pride in being Irnen Boys, or the Hawkers of [location] dub themselves the Kettleblack Crew.

The Bosses however, are often the unsung players in the dance of the Families. Since most cross the lines of territory, involving themselves in a variety of spheres, they are seldom claimed by one Family. Their gangs might be assigned to one, but the Boss herself is the player that can cross the walls, and build the webs.

=== The Six Families:
Irnen::
Sphere: Power

Kettleblack::
Sphere: Shipping and transportation

Tradd::
Sphere: Food

Vyros::
Sphere: The University

Braskenohr::
//

Crowlin::
//

NOTE: Leviathan Blood and the Goodsmith Refinery are not the province of any of the Six Families, and are firmly the property of the Ministry of Preservation.

== Races and Racial Interactions
While there are Serverosi and Iruvians in Lockport, they are few and far between. The majority of the citizenry is composed of a mixture of Akorosi and Skovlanders. There has also been a sharp up-tic in the number of Tycherosi in the city in recent years.

Due to the fact that the city has changed hands so many times over the past years, its culture is a relatively cosmopolitan blend.

While Lockport is technically part of Skovland, the city is largely led by the Akarosi. With their inborn drive to succeed, and bring betterment to the world, they tend to take on the most influential and powerful roles. Due to their inherently less ambitious nature, most Skovlanders occupy lower to middle class occupations and roles.

Of the Six Families, only one, Braskenohr, is of old Skovlander blood, again demonstrating that race’s natural need for leadership. Two have mixed heritage, Crowlin and Irnen. Vyros, Tradd, and Kettleblack have limited their adulteration in their lineage.

All government business and signage is written in Akorosian, however the majority of the population speaks and reads Skovic with equal facility. Other languages are spoken within homes and family units, but are not generally part of public life.

Tycherosi are commonplace in Lockport. Though they’re generally seen as needing to prove their worth, they are assumed to have the ability to do so. It’s odd, though, that there seem to be no Tycherosi immigrants. No one seems to have met someone who came her from the far distant land. Rather, all the Strangers in Lockport were born in the Shattered Isles.

== The In-Human
